# Generated by Django 4.0.6 on 2022-07-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_bola',
            name='text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
