# Generated by Django 4.0.6 on 2022-07-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_team_bola_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kurslarimiz_soni', models.IntegerField()),
                ('Oquvchilarimiz', models.IntegerField()),
                ('Ishga_joylashganlar', models.IntegerField()),
                ('Mentorlar', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='team',
            old_name='tag',
            new_name='sohasi',
        ),
        migrations.AddField(
            model_name='team',
            name='img',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
