# Generated by Django 4.0.6 on 2022-07-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_team_bola_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurslar_soni', models.IntegerField()),
                ('uquvchilar_soni', models.IntegerField()),
                ('ishga_joylashganlar', models.IntegerField()),
                ('mentorlar', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='img',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='sohasi',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
