# Generated by Django 4.0.6 on 2022-07-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_team_bola_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coueres',
            name='coueres_price',
        ),
        migrations.AddField(
            model_name='coueres',
            name='narx',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Coueres_price',
        ),
    ]
