# Generated by Django 4.0.6 on 2022-07-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_statika_rename_tag_team_sohasi_team_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
