# Generated by Django 4.0.6 on 2022-07-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_statika_team_img_team_sohasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coueres',
            name='coueres_price',
        ),
        migrations.AddField(
            model_name='coueres',
            name='price',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Coueres_price',
        ),
    ]
