# Generated by Django 4.0.6 on 2022-07-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_team_img_alter_team_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='text',
            field=models.CharField(max_length=250),
        ),
    ]
