# Generated by Django 4.1.1 on 2022-09-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_coueres_coueres_price_coueres_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nimadir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
