# Generated by Django 4.0.6 on 2022-07-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_team_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statika',
            old_name='Ishga_joylashganlar',
            new_name='ishga_joylashganlar',
        ),
        migrations.RenameField(
            model_name='statika',
            old_name='Kurslarimiz_soni',
            new_name='kurslar_soni',
        ),
        migrations.RenameField(
            model_name='statika',
            old_name='Mentorlar',
            new_name='mentorlar',
        ),
        migrations.RenameField(
            model_name='statika',
            old_name='Oquvchilarimiz',
            new_name='uquvchilar_soni',
        ),
    ]
